services:
  laravel-app:
    image: ${REGISTRY:-localhost}/runarion-app-laravel:${TAG:-latest}
    build:
      context: ./runarion-laravel
      dockerfile: dockerfile
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: ${LARAVEL_MEMORY_LIMIT:-2048M}
        reservations:
          memory: ${LARAVEL_MEMORY_RESERVATION:-1024M}
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL:-http://localhost}
      DB_CONNECTION: pgsql
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_DATABASE: runarion
      DB_USERNAME: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      PYTHON_SERVICE_URL: http://runarion-python:5000
      APP_LOCALE: ${APP_LOCALE:-en}
      APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE:-en}
      APP_FAKER_LOCALE: ${APP_FAKER_LOCALE:-en_US}
      PHP_CLI_SERVER_WORKERS: ${PHP_CLI_SERVER_WORKERS:-4}
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-12}
    networks:
      - runarion-app-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-3}
    command: >
      sh -c "php artisan key:generate --force &&
             php artisan config:cache &&
             php artisan route:cache &&
             php artisan view:cache &&
             php artisan serve --host=0.0.0.0 --port=8000"

  python-app:
    image: ${REGISTRY:-localhost}/runarion-app-runarion-python:${TAG:-latest}
    build:
      context: ./runarion-python
      dockerfile: dockerfile
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: ${PYTHON_MEMORY_LIMIT:-1024M}
        reservations:
          memory: ${PYTHON_MEMORY_RESERVATION:-512M}
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: production
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: runarion
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - runarion-app-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-3}

  postgres-db:
    image: postgres:14
    deploy:
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: runarion
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - runarion-app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-3}

networks:
  runarion-app-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
