services:
  laravel-app:
    build:
      context: ./runarion-laravel
      dockerfile: dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_DATABASE: runarion
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD:-@kb4r123}
      PYTHON_SERVICE_URL: http://localhost:5000
      APP_LOCALE: ${APP_LOCALE:-en}
      APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE:-en}
      APP_FAKER_LOCALE: ${APP_FAKER_LOCALE:-en_US}
      PHP_CLI_SERVER_WORKERS: ${PHP_CLI_SERVER_WORKERS:-4}
      BCRYPT_ROUNDS: ${BCRYPT_ROUNDS:-12}
      VITE_PORT: 5173
      VITE_HOST: 0.0.0.0
      VITE_SERVICE_URL: http://localhost:5173
    volumes:
      - ./runarion-laravel:/var/www/html
      - /var/www/html/node_modules
    networks:
      - runarion-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-3}
    deploy:
      resources:
        limits:
          memory: ${LARAVEL_MEMORY_LIMIT:-2048M}
        reservations:
          memory: ${LARAVEL_MEMORY_RESERVATION:-1024M}
    command: ["/bin/bash", "/var/www/html/docker-entrypoint-dev.sh"]
             
  python-app:
    build:
      context: ./runarion-python
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: development
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: runarion
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-@kb4r123}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-your-gemini-api-key-here}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-your-google-api-key-here}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-openai-api-key-here}
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    volumes:
      - ./runarion-python:/app
      - /app/venv
    networks:
      - runarion-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-3}
    deploy:
      resources:
        limits:
          memory: ${PYTHON_MEMORY_LIMIT:-1024M}
        reservations:
          memory: ${PYTHON_MEMORY_RESERVATION:-512M}
    command: ["/bin/bash", "/app/docker-entrypoint-dev.sh"]
          
  postgres-db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: runarion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-@kb4r123}
    networks:
      - runarion-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-3}

networks:
  runarion-network:
    driver: bridge

volumes:
  postgres_data:
