"""
Stage 7: Chaptering

Organizes the final manuscript into well-structured chapters with titles.

MIGRATION NOTES (v1.x → v2.0):
===============================
The chaptering architecture was refactored in v2.0 to separate AI decision-making
from content assembly.

KEY CHANGES:
- AI now returns structure only (scene ranges + titles), not content
- Content is assembled from database scenes, not generated by AI
- Token limit reduced from 4500 → 1000 (90% reduction)
- Constrained fallback now uses scene boundaries instead of word count

DEPRECATED METHODS (removal scheduled for v3.0):
- _process_ai_chaptering() → use _build_chapters_from_structure()
- _generate_chapter_titles() → titles now from AI structure
- _ai_generate_title() → titles now from AI structure
- _find_scene_breaks_in_text() → work with scene records directly
- _find_best_chapter_break() → chapters break on scene boundaries

If you see deprecation warnings in logs, update calling code.
"""

import json
import logging
import re
from typing import Dict, Any, List, Tuple, Optional
from datetime import datetime
from ulid import ULID
from .prompt_template import DeconstructorPrompts
from utils.database_utils import clean_text_for_database, ensure_utf8_json
from utils.llm_retry import call_llm_with_retry
from .base_stage import BasePipelineStage, PipelineStageResult, PipelineStageContext

logger = logging.getLogger(__name__)

class ChapteringStage(BasePipelineStage):
    """
    Stage 7 of the deconstruction pipeline.
    Organizes final manuscript into logical chapters with compelling titles.

    ARCHITECTURE (v2.0+):
    ---------------------
    This stage uses a two-phase approach:

    Phase 1 - AI Structure Planning:
      - AI analyzes scene summaries and determines chapter breaks
      - Returns minimal JSON structure (scene ranges + titles)
      - Token usage: ~300-500 tokens

    Phase 2 - System Assembly:
      - System queries database for enhanced scene content
      - Concatenates scenes according to AI structure
      - Stores complete chapters in database

    BENEFITS:
    - 90% reduction in API token usage
    - No token truncation possible
    - Content comes from already-enhanced scenes
    - Scales to unlimited document sizes

    FALLBACK:
    If AI structure planning fails, falls back to simple scene-based
    division with equal chapter lengths.
    """
    
    def __init__(self, db_pool, generation_engine):
        """
        Initialize the chaptering stage.
        
        Args:
            db_pool: Database connection pool
            generation_engine: AI generation engine
        """
        super().__init__(db_pool, "ChapteringStage", generation_engine)
        self.prompt_template = DeconstructorPrompts()
    
    def _execute_stage(self, context: PipelineStageContext) -> PipelineStageResult:
        """
        Execute Stage 7: Chapter organization.
        
        Args:
            context: Stage execution context containing draft_id
            
        Returns:
            PipelineStageResult with stage execution results
        """
        draft_id = context.draft_id

        # Store context for use in validation (needed by _validate_chapter_structure)
        self.current_context = context

        # Get chaptering parameters from draft metadata
        draft_metadata = self.get_draft_metadata(draft_id)
        chaptering_mode = draft_metadata.get('chaptering_mode', 'flexible')
        target_chapter_length = draft_metadata.get('target_chapter_length', 2500)
        
        try:
            # Get final manuscript
            manuscript_data = self._get_final_manuscript(context)
            
            if not manuscript_data:
                return PipelineStageResult.success_result(
                    self.stage_name,
                    chapters_created=0,
                    message='No final manuscript to chapter'
                )
            
            # Get scene information for chapter break guidance
            scene_info = self._get_scene_information(context)
            
            # Perform chaptering based on mode
            if chaptering_mode == 'constrained':
                chapters = self._constrained_chaptering(
                    manuscript_data['content'], 
                    scene_info, 
                    target_chapter_length
                )
            else:  # flexible mode (default)
                chapters = self._flexible_chaptering(
                    manuscript_data['content'], 
                    scene_info, 
                    target_chapter_length
                )
            
            # Titles now come from AI structure or constrained fallback - no post-processing needed
            chapters_with_titles = chapters  # Rename variable for clarity

            # Validate chapter boundaries for pacing integrity (diagnostic + gate signal)
            boundary_validation = self._validate_boundary_pacing(chapters_with_titles, scene_info)

            # Store chapters in database
            chapters_stored = self._store_chapters(context, chapters_with_titles)
            
            # Calculate statistics
            total_word_count = sum(chapter.get('word_count', 0) for chapter in chapters_with_titles)
            
            return PipelineStageResult.success_result(
                self.stage_name,
                chapters_created=len(chapters_with_titles),
                chapters_stored=chapters_stored,
                total_word_count=total_word_count,
                chaptering_mode=chaptering_mode,
                target_chapter_length=target_chapter_length,
                avg_chapter_length=total_word_count // len(chapters_with_titles) if chapters_with_titles else 0,
                manuscript_word_count=manuscript_data['word_count'],
                boundary_validation=boundary_validation,
            )
            
        except Exception as e:
            return PipelineStageResult.error_result(
                self.stage_name,
                error=str(e),
                draft_id=draft_id
            )
    
    def run(self, draft_id: str, chaptering_mode: str = 'flexible', 
           target_chapter_length: int = 2500) -> Dict[str, Any]:
        """
        Execute Stage 7 with legacy interface (backward compatibility).
        
        Args:
            draft_id: UUID of the draft
            chaptering_mode: Chaptering approach (backward compatibility)
            target_chapter_length: Target word count (backward compatibility)
            
        Returns:
            Stage execution results
        """
        return super().run(draft_id)
    
    def _get_final_manuscript(self, context: PipelineStageContext) -> Optional[Dict[str, Any]]:
        """
        Retrieve the final manuscript for chaptering.
        
        Args:
            context: Stage execution context
            
        Returns:
            Manuscript data or None if not found
        """
        draft_id = context.draft_id
        
        try:
            db_connection = self.get_database_connection(context)
            with db_connection as conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT final_content, word_count, generated_at
                    FROM final_manuscripts
                    WHERE draft_id = %s
                    ORDER BY generated_at DESC
                    LIMIT 1
                """, (draft_id,))
                
                result = cursor.fetchone()
                
                if not result:
                    return None
                
                content, word_count, generated_at = result
                
                manuscript_data = {
                    'content': content,
                    'word_count': word_count,
                    'generated_at': generated_at
                }
            
            self.logger.debug(f"Retrieved final manuscript for draft {draft_id}: {word_count} words")
            return manuscript_data
            
        except Exception as e:
            self.logger.error(f"Failed to retrieve final manuscript for draft {draft_id}: {e}")
            return None
    
    def _get_scene_information(self, context: PipelineStageContext) -> List[Dict[str, Any]]:
        """
        Get scene information to guide chapter breaks.
        
        Args:
            context: Stage execution context
            
        Returns:
            List of scene information
        """
        draft_id = context.draft_id
        
        try:
            scene_info = []
            
            db_connection = self.get_database_connection(context)
            with db_connection as conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT scene_number, title, setting, characters, analysis_json
                    FROM scenes
                    WHERE draft_id = %s
                    ORDER BY scene_number
                """, (draft_id,))
                
                scenes = cursor.fetchall()
                
                for scene in scenes:
                    scene_number, title, setting, characters, analysis_json = scene
                    
                    try:
                        analysis = json.loads(analysis_json) if analysis_json else {}
                        characters_list = json.loads(characters) if characters else []
                    except (json.JSONDecodeError, TypeError):
                        analysis = {}
                        characters_list = []
                    
                    scene_info.append({
                        'scene_number': scene_number,
                        'title': title,
                        'setting': setting,
                        'characters': characters_list,
                        'plot_function': analysis.get('plot_function', ''),
                        'significance': analysis.get('overall_significance', ''),
                        'conflicts': analysis.get('conflicts', [])
                    })
            
            self.logger.debug(f"Retrieved scene information for {len(scene_info)} scenes")
            return scene_info
            
        except Exception as e:
            self.logger.error(f"Failed to retrieve scene information for draft {draft_id}: {e}")
            return []
    
    def _flexible_chaptering(self, manuscript: str, scene_info: List[Dict[str, Any]],
                           target_length: int) -> List[Dict[str, Any]]:
        """
        Create chapters using AI-guided structural decisions.

        NEW ARCHITECTURE: AI returns chapter structure (scene ranges + titles) only,
        then system assembles content from database scenes.

        Args:
            manuscript: Full manuscript text (unused, kept for compatibility)
            scene_info: Scene information for AI analysis
            target_length: Target chapter length (used for chapter count estimation)

        Returns:
            List of complete chapter data with assembled content
        """
        try:
            # Calculate target chapter count range
            total_scenes = len(scene_info)
            min_chapters = max(2, total_scenes // 5)  # Rough estimate: ~5 scenes per chapter
            max_chapters = max(3, total_scenes // 3)  # ~3 scenes per chapter minimum

            # Prepare concise scene information for AI
            scene_summary = []
            for scene in scene_info:
                summary = (
                    f"Scene {scene['scene_number']}: {scene['title']}"
                )
                # Add significance if available (first 100 chars)
                if scene.get('significance'):
                    summary += f" - {scene['significance'][:100]}"
                elif scene.get('plot_function'):
                    summary += f" - {scene['plot_function'][:100]}"
                scene_summary.append(summary)

            # Build prompt requesting structure only
            prompt = self.prompt_template.get_chaptering_prompt().format(
                scene_information='\n'.join(scene_summary),
                total_scenes=total_scenes,
                min_chapters=min_chapters,
                max_chapters=max_chapters,
                chaptering_mode='flexible'
            )

            self.generation_engine.request.prompt = prompt
            self.generation_engine.request.instruction = (
                f"Analyze {total_scenes} scenes and create {min_chapters}-{max_chapters} "
                f"chapters with natural narrative breaks."
            )

            # Provider-aware token limit for chaptering structure JSON
            self.generation_engine.request.generation_config.max_output_tokens = self._get_output_budget("json_analytical")

            # Enable JSON mode for Gemini structured output
            self.generation_engine.request.generation_config.response_mime_type = "application/json"

            try:
                # Wrap with transient-error retry even though token requirement
                # is low — a 503 spike would still cause a needless failure.
                response = call_llm_with_retry(
                    lambda: self.generation_engine.generate(skip_quota=True)
                )
            finally:
                # Reset to avoid leaking into subsequent plain-text stages
                self.generation_engine.request.generation_config.response_mime_type = None

            if response.success:
                try:
                    # Parse AI response
                    from utils.json_response_parser import JSONResponseParser
                    ai_structure, _ = JSONResponseParser.parse_response(response, "dict", {})

                    # Validate structure
                    if not self._validate_chapter_structure(ai_structure, self.current_context):
                        self.logger.warning(
                            "AI-generated chapter structure failed validation. "
                            "Falling back to constrained chaptering."
                        )
                        return self._constrained_chaptering(manuscript, scene_info, target_length)

                    # Build chapters from validated structure
                    return self._build_chapters_from_structure(ai_structure, self.current_context)

                except Exception as parse_error:
                    self.logger.warning(
                        f"Could not parse or build AI chaptering structure: {parse_error}. "
                        f"Falling back to constrained approach."
                    )
                    return self._constrained_chaptering(manuscript, scene_info, target_length)
            else:
                self.logger.warning(
                    f"AI chaptering failed: {response.error}. Using constrained approach."
                )
                return self._constrained_chaptering(manuscript, scene_info, target_length)

        except Exception as e:
            self.logger.error(f"Error in flexible chaptering: {e}")
            return self._constrained_chaptering(manuscript, scene_info, target_length)

    def _build_chapters_from_structure(
        self,
        structure: Dict[str, Any],
        context: PipelineStageContext
    ) -> List[Dict[str, Any]]:
        """
        Build complete chapters by querying database for enhanced scene content.

        This is the new assembly layer that separates AI decision-making from
        data retrieval and formatting.

        Args:
            structure: AI-generated chapter structure with scene ranges and titles
            context: Pipeline context containing draft_id and DB connection

        Returns:
            List of complete chapter data ready for storage

        Raises:
            ValueError: If structure validation fails
        """
        draft_id = context.draft_id
        chapters = []

        try:
            # Validate structure before processing
            if not self._validate_chapter_structure(structure, context):
                raise ValueError("Invalid chapter structure: scene coverage incomplete")

            # Get database connection (use transaction if available)
            db_conn = self.get_database_connection(context)

            for chapter_spec in structure.get('chapters', []):
                chapter_num = chapter_spec['chapter_number']
                start_scene = chapter_spec['start_scene']
                end_scene = chapter_spec['end_scene']
                title = chapter_spec['title']
                rationale = chapter_spec.get('rationale', '')

                self.logger.debug(
                    f"Building chapter {chapter_num}: scenes {start_scene}-{end_scene}"
                )

                # Query enhanced scenes from database
                with db_conn.cursor() as cursor:
                    cursor.execute("""
                        SELECT scene_number, title, enhanced_content, original_content
                        FROM scenes
                        WHERE draft_id = %s
                          AND scene_number BETWEEN %s AND %s
                        ORDER BY scene_number ASC
                    """, (draft_id, start_scene, end_scene))

                    scene_rows = cursor.fetchall()

                # Validate we got all expected scenes
                if len(scene_rows) != (end_scene - start_scene + 1):
                    self.logger.warning(
                        f"Chapter {chapter_num}: Expected {end_scene - start_scene + 1} scenes, "
                        f"got {len(scene_rows)}. Some scenes may be missing from database."
                    )

                # Assemble chapter content from scenes
                chapter_content_parts = []
                scene_titles = []

                for scene_num, scene_title, enhanced_content, original_content in scene_rows:
                    scene_titles.append(scene_title)

                    # Use enhanced content if available, otherwise fall back to original
                    content_to_use = enhanced_content if enhanced_content else original_content

                    if not content_to_use:
                        self.logger.warning(f"Scene {scene_num} has no content!")
                        continue

                    # Add scene separator for readability (optional formatting)
                    chapter_content_parts.append(f"\n\n=== {scene_title} ===\n\n")
                    chapter_content_parts.append(content_to_use)

                # Concatenate all scene content
                full_content = ''.join(chapter_content_parts).strip()
                word_count = len(full_content.split())

                # Build chapter data structure
                chapters.append({
                    'chapter_number': chapter_num,
                    'title': title,
                    'content': full_content,
                    'word_count': word_count,
                    'start_scene': start_scene,
                    'end_scene': end_scene,
                    'scene_count': end_scene - start_scene + 1,
                    'scene_titles': scene_titles,
                    'rationale': rationale,
                })

                self.logger.info(
                    f"Chapter {chapter_num} assembled: {word_count} words from "
                    f"{len(scene_rows)} scenes"
                )

            return chapters

        except Exception as e:
            self.logger.error(f"Failed to build chapters from structure: {e}")
            raise

    def _validate_chapter_structure(
        self,
        structure: Dict[str, Any],
        context: PipelineStageContext
    ) -> bool:
        """
        Validate that AI-generated chapter structure is complete and correct.

        Checks:
        1. All scenes are included exactly once
        2. Scenes are consecutive (no gaps or overlaps)
        3. First chapter starts at scene 1
        4. Last chapter ends at final scene

        Args:
            structure: AI-generated chapter structure
            context: Pipeline context containing draft_id

        Returns:
            True if valid, False otherwise
        """
        draft_id = context.draft_id
        chapters = structure.get('chapters', [])

        if not chapters:
            self.logger.error("Chapter structure is empty")
            return False

        try:
            # Get total scene count from database
            db_conn = self.get_database_connection(context)
            with db_conn.cursor() as cursor:
                cursor.execute("""
                    SELECT COUNT(*) FROM scenes WHERE draft_id = %s
                """, (draft_id,))
                total_scenes = cursor.fetchone()[0]

            if total_scenes == 0:
                self.logger.error("No scenes found in database for validation")
                return False

            # Sort chapters by chapter_number to ensure correct order
            sorted_chapters = sorted(chapters, key=lambda c: c['chapter_number'])

            # Check first chapter starts at scene 1
            if sorted_chapters[0]['start_scene'] != 1:
                self.logger.error(
                    f"First chapter starts at scene {sorted_chapters[0]['start_scene']}, "
                    "expected scene 1"
                )
                return False

            # Check consecutiveness and coverage
            covered_scenes = set()
            prev_end = 0

            for chapter in sorted_chapters:
                start = chapter['start_scene']
                end = chapter['end_scene']

                # Check for gaps
                if start != prev_end + 1:
                    self.logger.error(
                        f"Gap detected: Chapter {chapter['chapter_number']} starts at "
                        f"scene {start}, expected {prev_end + 1}"
                    )
                    return False

                # Check for valid range
                if end < start:
                    self.logger.error(
                        f"Invalid range in chapter {chapter['chapter_number']}: "
                        f"end_scene ({end}) < start_scene ({start})"
                    )
                    return False

                # Track covered scenes
                for scene_num in range(start, end + 1):
                    if scene_num in covered_scenes:
                        self.logger.error(
                            f"Scene {scene_num} assigned to multiple chapters"
                        )
                        return False
                    covered_scenes.add(scene_num)

                prev_end = end

            # Check last chapter ends at final scene
            if prev_end != total_scenes:
                self.logger.error(
                    f"Last chapter ends at scene {prev_end}, expected scene {total_scenes}"
                )
                return False

            self.logger.info(
                f"Chapter structure validated: {len(sorted_chapters)} chapters "
                f"covering {total_scenes} scenes"
            )
            return True

        except Exception as e:
            self.logger.error(f"Error validating chapter structure: {e}")
            return False

    def _constrained_chaptering(self, manuscript: str, scene_info: List[Dict[str, Any]],
                              target_length: int) -> List[Dict[str, Any]]:
        """
        Create chapters using simple scene-based division (fallback when AI fails).

        NEW APPROACH: Divide scenes into equal groups instead of splitting by word count.
        This ensures chapter breaks align with natural scene boundaries.

        Args:
            manuscript: Full manuscript text (unused)
            scene_info: Scene information
            target_length: Target chapter length in words (used for chapter count estimation)

        Returns:
            List of chapter data
        """
        try:
            total_scenes = len(scene_info)

            if total_scenes == 0:
                self.logger.error("No scenes available for constrained chaptering")
                return []

            # Estimate chapter count based on average scene length
            # Assume average scene is ~500 words
            estimated_scenes_per_chapter = max(3, target_length // 500)
            estimated_chapters = max(1, total_scenes // estimated_scenes_per_chapter)

            # Calculate scenes per chapter (roughly equal distribution)
            scenes_per_chapter = total_scenes // estimated_chapters
            remainder_scenes = total_scenes % estimated_chapters

            self.logger.info(
                f"Constrained chaptering: dividing {total_scenes} scenes into "
                f"{estimated_chapters} chapters (~{scenes_per_chapter} scenes each)"
            )

            # Build simple chapter structure
            chapters = []
            current_scene = 1

            for chapter_num in range(1, estimated_chapters + 1):
                # Distribute remainder scenes across first N chapters
                extra_scene = 1 if chapter_num <= remainder_scenes else 0
                chapter_scene_count = scenes_per_chapter + extra_scene

                start_scene = current_scene
                end_scene = min(current_scene + chapter_scene_count - 1, total_scenes)

                # Generate simple title from first scene in chapter
                chapter_title = self._create_fallback_title_from_scenes(
                    scene_info,
                    start_scene,
                    end_scene,
                    chapter_num
                )

                chapters.append({
                    'chapter_number': chapter_num,
                    'title': chapter_title,
                    'start_scene': start_scene,
                    'end_scene': end_scene,
                    'rationale': 'Constrained fallback grouped by contiguous scene ranges.',
                })

                current_scene = end_scene + 1

                # Safety check: if we've covered all scenes, break
                if current_scene > total_scenes:
                    break

            # Build chapter structure format expected by assembly method
            structure = {
                'chapters': chapters,
                'structure_notes': 'Constrained equal-division fallback'
            }

            # Use same assembly method as flexible chaptering
            return self._build_chapters_from_structure(structure, self.current_context)

        except Exception as e:
            self.logger.error(f"Error in constrained chaptering: {e}")
            # Ultimate fallback: single chapter with all scenes
            return self._build_chapters_from_structure(
                {
                    'chapters': [{
                        'chapter_number': 1,
                        'title': 'Complete Manuscript',
                        'start_scene': 1,
                        'end_scene': len(scene_info)
                    }],
                    'structure_notes': 'Emergency single-chapter fallback'
                },
                self.current_context
            )

    def _validate_boundary_pacing(
        self,
        chapters: List[Dict[str, Any]],
        scene_info: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Heuristic validator for chapter-boundary pacing integrity.

        Flags boundaries that appear to split a continuous high-kinetic sequence
        without an explicit structural justification.
        """
        total_boundaries = max(0, len(chapters) - 1)
        if total_boundaries == 0:
            return {
                'total_boundaries': 0,
                'flagged_count': 0,
                'critical_flag_count': 0,
                'flag_ratio': 0.0,
                'critical_ratio': 0.0,
                'passes_gate': True,
                'flagged_boundaries': [],
            }

        scene_lookup = {
            int(scene.get('scene_number', 0)): scene
            for scene in scene_info
            if scene.get('scene_number') is not None
        }

        flagged_boundaries: List[Dict[str, Any]] = []
        critical_flag_count = 0

        for idx in range(total_boundaries):
            left_chapter = chapters[idx]
            right_chapter = chapters[idx + 1]

            left_end_scene_num = int(left_chapter.get('end_scene', 0) or 0)
            right_start_scene_num = int(right_chapter.get('start_scene', 0) or 0)

            left_scene = scene_lookup.get(left_end_scene_num, {})
            right_scene = scene_lookup.get(right_start_scene_num, {})

            left_intensity = self._scene_action_intensity(left_scene)
            right_intensity = self._scene_action_intensity(right_scene)
            overlap_ratio = self._character_overlap_ratio(left_scene, right_scene)
            same_setting = bool(left_scene.get('setting') and left_scene.get('setting') == right_scene.get('setting'))

            continuity_signals: List[str] = []
            if left_intensity >= 0.72 and right_intensity >= 0.72:
                continuity_signals.append('high_action_on_both_sides')
            if overlap_ratio >= 0.6:
                continuity_signals.append('high_character_overlap')
            if same_setting:
                continuity_signals.append('same_setting')

            if not continuity_signals:
                continue

            if self._is_boundary_justified(left_scene, right_scene, left_chapter, right_chapter):
                continue

            severity = 'critical' if (
                left_intensity >= 0.78
                and right_intensity >= 0.78
                and overlap_ratio >= 0.5
            ) else 'warning'

            if severity == 'critical':
                critical_flag_count += 1

            flagged_boundaries.append({
                'boundary_after_chapter': int(left_chapter.get('chapter_number', idx + 1)),
                'left_scene': left_end_scene_num,
                'right_scene': right_start_scene_num,
                'left_intensity': round(left_intensity, 2),
                'right_intensity': round(right_intensity, 2),
                'character_overlap_ratio': round(overlap_ratio, 2),
                'signals': continuity_signals,
                'severity': severity,
                'left_rationale': (left_chapter.get('rationale') or '')[:200],
                'right_rationale': (right_chapter.get('rationale') or '')[:200],
            })

        flagged_count = len(flagged_boundaries)
        flag_ratio = flagged_count / total_boundaries if total_boundaries else 0.0
        critical_ratio = critical_flag_count / total_boundaries if total_boundaries else 0.0

        # Gate policy: fail only when majority of boundaries are critically problematic.
        passes_gate = critical_ratio <= 0.5

        return {
            'total_boundaries': total_boundaries,
            'flagged_count': flagged_count,
            'critical_flag_count': critical_flag_count,
            'flag_ratio': round(flag_ratio, 2),
            'critical_ratio': round(critical_ratio, 2),
            'passes_gate': passes_gate,
            'flagged_boundaries': flagged_boundaries,
        }

    def _scene_action_intensity(self, scene: Dict[str, Any]) -> float:
        """Estimate kinetic/action intensity of a scene from descriptive signals."""
        if not scene:
            return 0.0

        parts = [
            str(scene.get('title', '') or ''),
            str(scene.get('plot_function', '') or ''),
            str(scene.get('significance', '') or ''),
        ]
        conflicts = scene.get('conflicts') or []
        if isinstance(conflicts, list):
            parts.extend(str(c) for c in conflicts)
        else:
            parts.append(str(conflicts))

        signal_text = " ".join(parts).lower()
        if not signal_text.strip():
            return 0.0

        action_keywords = [
            'fight', 'battle', 'attack', 'ambush', 'gun', 'gunfire', 'shoot', 'shootout',
            'chase', 'escape', 'pursuit', 'explode', 'explosion', 'kill', 'stab', 'strike',
            'confront', 'violence', 'blood', 'riot', 'panic', 'crash', 'raid', 'hunt',
        ]

        matches = sum(1 for word in action_keywords if word in signal_text)
        base = min(1.0, matches / 7.0)

        # Short explicit conflict blurbs should still score non-trivially.
        if matches > 0 and len(signal_text) < 120:
            base = min(1.0, base + 0.08)

        return round(base, 2)

    def _character_overlap_ratio(
        self,
        left_scene: Dict[str, Any],
        right_scene: Dict[str, Any],
    ) -> float:
        """Return Jaccard overlap for character sets across adjacent scenes."""
        left_chars = left_scene.get('characters') or []
        right_chars = right_scene.get('characters') or []

        if isinstance(left_chars, str):
            left_chars = [left_chars]
        if isinstance(right_chars, str):
            right_chars = [right_chars]

        left_set = {str(c).strip().lower() for c in left_chars if str(c).strip()}
        right_set = {str(c).strip().lower() for c in right_chars if str(c).strip()}

        union = left_set | right_set
        if not union:
            return 0.0
        return len(left_set & right_set) / len(union)

    def _is_boundary_justified(
        self,
        left_scene: Dict[str, Any],
        right_scene: Dict[str, Any],
        left_chapter: Dict[str, Any],
        right_chapter: Dict[str, Any],
    ) -> bool:
        """
        Determine whether a potentially risky boundary has explicit justification.
        """
        rationale_text = " ".join([
            str(left_chapter.get('rationale', '') or ''),
            str(right_chapter.get('rationale', '') or ''),
        ]).lower()

        justification_keywords = [
            'time jump', 'later', 'hours later', 'days later', 'aftermath', 'meanwhile',
            'new location', 'location shift', 'perspective shift', 'flashback',
            'interlude', 'cooldown', 'recovery', 'transition', 'thematic pivot',
        ]
        if any(keyword in rationale_text for keyword in justification_keywords):
            return True

        left_setting = str(left_scene.get('setting', '') or '').strip().lower()
        right_setting = str(right_scene.get('setting', '') or '').strip().lower()
        if left_setting and right_setting and left_setting != right_setting:
            return True

        overlap_ratio = self._character_overlap_ratio(left_scene, right_scene)
        if overlap_ratio <= 0.2:
            return True

        return False
    
    def _find_scene_breaks_in_text(self, manuscript: str, scene_info: List[Dict[str, Any]]) -> List[int]:
        """
        [DEPRECATED] Find approximate positions of scene breaks in manuscript text.

        No longer used in v2.0+ as we work with scene database records directly.
        Kept for potential legacy use cases.

        Args:
            manuscript: Full manuscript text
            scene_info: Scene information

        Returns:
            List of word positions where scenes likely break
        """
        self.logger.warning("DEPRECATED: _find_scene_breaks_in_text() called")

        scene_breaks = []
        words = manuscript.split()

        try:
            # Look for scene markers in the text
            scene_markers = [
                '=== ',  # Scene headers we added
                'Chapter ',
                '\n\n\n',  # Multiple line breaks
                '* * *',   # Scene separators
                '---'      # Dashes
            ]
            
            text_lower = manuscript.lower()
            
            for i, word in enumerate(words):
                # Check if this position might be a scene break
                word_position = manuscript.lower().find(word.lower())
                
                # Look for scene markers near this position
                for marker in scene_markers:
                    marker_pos = text_lower.find(marker.lower(), max(0, word_position - 50))
                    if marker_pos != -1 and abs(marker_pos - word_position) < 100:
                        scene_breaks.append(i)
                        break
            
            # Also add breaks based on scene titles
            for scene in scene_info:
                scene_title = scene['title'].lower()
                title_pos = text_lower.find(scene_title)
                if title_pos != -1:
                    # Find approximate word position
                    word_pos = len(manuscript[:title_pos].split())
                    if word_pos not in scene_breaks:
                        scene_breaks.append(word_pos)
            
            # Sort and remove duplicates
            scene_breaks = sorted(list(set(scene_breaks)))
            
            self.logger.debug(f"Found {len(scene_breaks)} potential scene breaks")
            return scene_breaks
            
        except Exception as e:
            self.logger.warning(f"Error finding scene breaks: {e}")
            return []
    
    def _find_best_chapter_break(self, scene_breaks: List[int], start_pos: int,
                               target_pos: int, words: List[str]) -> int:
        """
        [DEPRECATED] Find best chapter break position near target.

        No longer used in v2.0+ as chapters break on scene boundaries only.
        Kept for potential legacy use cases.

        Args:
            scene_breaks: List of potential scene break positions
            start_pos: Chapter start position
            target_pos: Target chapter end position
            words: All words in the manuscript

        Returns:
            Best chapter break position
        """
        self.logger.warning("DEPRECATED: _find_best_chapter_break() called")

        try:
            # Filter scene breaks to those in our range
            candidate_breaks = [
                pos for pos in scene_breaks 
                if start_pos < pos <= target_pos + 500  # Allow some overage
            ]
            
            if not candidate_breaks:
                # No scene breaks found, look for natural paragraph breaks
                return self._find_paragraph_break(start_pos, target_pos, words)
            
            # Find the break closest to our target
            best_break = min(candidate_breaks, key=lambda x: abs(x - target_pos))
            
            # Don't allow chapters that are too short
            min_chapter_length = 500  # Minimum 500 words
            if best_break - start_pos < min_chapter_length:
                # Look for a later break
                later_breaks = [pos for pos in candidate_breaks if pos - start_pos >= min_chapter_length]
                if later_breaks:
                    best_break = min(later_breaks, key=lambda x: abs(x - target_pos))
            
            return best_break
            
        except Exception as e:
            self.logger.warning(f"Error finding best chapter break: {e}")
            return target_pos
    
    def _find_paragraph_break(self, start_pos: int, target_pos: int, words: List[str]) -> int:
        """
        Find a natural paragraph break near the target position.
        
        Args:
            start_pos: Chapter start position
            target_pos: Target chapter end position
            words: All words in the manuscript
            
        Returns:
            Paragraph break position
        """
        try:
            # Look for paragraph endings (words ending with . ! ? followed by capitalized words)
            search_range = range(max(start_pos, target_pos - 200), min(len(words), target_pos + 200))
            
            for i in search_range:
                if i < len(words) - 1:
                    current_word = words[i].strip()
                    next_word = words[i + 1].strip()
                    
                    # Check for sentence ending
                    if (current_word.endswith(('.', '!', '?')) and 
                        next_word and next_word[0].isupper()):
                        return i + 1
            
            # If no good break found, just use target position
            return min(target_pos, len(words))
            
        except Exception as e:
            self.logger.warning(f"Error finding paragraph break: {e}")
            return target_pos
    
    def _process_ai_chaptering(self, ai_result: Dict[str, Any], manuscript: str) -> List[Dict[str, Any]]:
        """
        [DEPRECATED] Process AI chaptering results into standard format.

        **This method is deprecated as of v2.0 and will be removed in v3.0.**
        The new architecture uses _build_chapters_from_structure() instead.

        This method is kept for backward compatibility but should not be called.
        If you see this in logs, update your code to use the new flow.

        Args:
            ai_result: AI chaptering analysis (old format)
            manuscript: Full manuscript text

        Returns:
            Processed chapter data (old format)
        """
        self.logger.warning(
            "DEPRECATED: _process_ai_chaptering() called. "
            "This method is deprecated and will be removed in v3.0. "
            "Use _build_chapters_from_structure() instead."
        )

        try:
            chapters = []
            ai_chapters = ai_result.get('chapters', [])
            
            if not ai_chapters:
                # Fallback to simple division
                words = manuscript.split()
                chapter_size = len(words) // 5  # Default to 5 chapters
                
                for i in range(5):
                    start = i * chapter_size
                    end = start + chapter_size if i < 4 else len(words)
                    
                    chapters.append({
                        'chapter_number': i + 1,
                        'content': ' '.join(words[start:end]),
                        'word_count': end - start,
                        'title': f'Chapter {i + 1}'
                    })
            else:
                # Process AI-generated chapters
                for ai_chapter in ai_chapters:
                    chapter_content = ai_chapter.get('content', '')
                    word_count = len(chapter_content.split()) if chapter_content else 0
                    
                    chapters.append({
                        'chapter_number': ai_chapter.get('chapter_number', len(chapters) + 1),
                        'content': chapter_content,
                        'word_count': word_count,
                        'title': ai_chapter.get('title', f"Chapter {len(chapters) + 1}"),
                        'summary': ai_chapter.get('summary', ''),
                        'key_events': ai_chapter.get('key_events', []),
                        'cliffhanger': ai_chapter.get('cliffhanger', 'No')
                    })
            
            return chapters
            
        except Exception as e:
            self.logger.error(f"Error processing AI chaptering: {e}")
            # Return single chapter as fallback
            return [{
                'chapter_number': 1,
                'content': manuscript,
                'word_count': len(manuscript.split()),
                'title': 'Chapter 1'
            }]
    
    def _generate_chapter_titles(self, chapters: List[Dict[str, Any]],
                               scene_info: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        [DEPRECATED] Generate compelling titles for chapters that don't have them.

        **This method is deprecated as of v2.0 and will be removed in v3.0.**
        The new architecture generates titles during structure planning, not post-hoc.

        This method is kept for backward compatibility but should not be called.

        Args:
            chapters: List of chapter data
            scene_info: Scene information for context

        Returns:
            Chapters with generated titles
        """
        self.logger.warning(
            "DEPRECATED: _generate_chapter_titles() called. "
            "Titles should now come from AI structure planning. "
            "This method will be removed in v3.0."
        )

        try:
            for chapter in chapters:
                # Skip if chapter already has a meaningful title
                current_title = chapter.get('title', '')
                if current_title and not current_title.startswith('Chapter '):
                    continue
                
                # Extract key content for title generation
                content = chapter.get('content', '')
                if not content:
                    continue
                
                # Get first few sentences for context
                sentences = content.split('.')[: 3]  # First 3 sentences
                context = '. '.join(sentences)[:500]  # Limit context length
                
                # Try to generate a title using AI
                generated_title = self._ai_generate_title(context, chapter['chapter_number'])
                
                if generated_title:
                    chapter['title'] = generated_title
                else:
                    # Fallback to descriptive title
                    chapter['title'] = self._create_fallback_title(content, chapter['chapter_number'])
            
            return chapters
            
        except Exception as e:
            self.logger.warning(f"Error generating chapter titles: {e}")
            # Ensure all chapters have titles
            for i, chapter in enumerate(chapters):
                if not chapter.get('title'):
                    chapter['title'] = f"Chapter {i + 1}"
            return chapters
    
    def _ai_generate_title(self, content_context: str, chapter_number: int) -> Optional[str]:
        """
        [DEPRECATED] Generate a chapter title using AI.

        No longer used in v2.0+ as titles come from AI structure planning.
        Kept for potential legacy use cases.

        Args:
            content_context: Chapter content context
            chapter_number: Chapter number

        Returns:
            Generated title or None if generation failed
        """
        self.logger.warning("DEPRECATED: _ai_generate_title() called")

        try:
            prompt = f"""Create a compelling, concise chapter title (2-5 words) for Chapter {chapter_number} based on this content:

{content_context}

The title should:
1. Capture the essence of the chapter
2. Be intriguing but not spoil major plot points
3. Fit the tone of the story
4. Be 2-5 words long

Respond with only the title, no quotes or explanation."""
            
            self.generation_engine.request.prompt = prompt
            self.generation_engine.request.instruction = f"Generate a chapter title for Chapter {chapter_number}."
            
            # Provider-aware token limit for short text
            self.generation_engine.request.generation_config.max_output_tokens = self._get_output_budget("short_text")
            
            response = call_llm_with_retry(
                lambda: self.generation_engine.generate(skip_quota=True)
            )

            if response.success:
                title = response.text.strip().strip('"').strip("'")
                
                # Validate title
                if len(title) > 0 and len(title.split()) <= 6:
                    return title
            
            return None
            
        except Exception as e:
            self.logger.warning(f"Error generating AI title for chapter {chapter_number}: {e}")
            return None
    
    def _create_fallback_title(self, content: str, chapter_number: int) -> str:
        """
        Create a fallback title based on content analysis.
        
        Args:
            content: Chapter content
            chapter_number: Chapter number
            
        Returns:
            Fallback title
        """
        try:
            # Extract key nouns and action words
            words = content.lower().split()[:200]  # First 200 words
            
            # Common action words that might make good titles
            action_words = ['battle', 'journey', 'discovery', 'escape', 'arrival', 'departure', 
                          'meeting', 'confrontation', 'revelation', 'decision', 'choice']
            
            # Look for action words in the content
            found_actions = [word for word in action_words if word in words]
            
            if found_actions:
                return f"The {found_actions[0].title()}"
            
            # Look for character names (capitalized words)
            capitalized = [word.strip('.,!?') for word in content.split() if word[0].isupper() and len(word) > 2]
            
            if capitalized:
                return f"{capitalized[0]}'s Tale"
            
            # Generic fallback
            return f"Chapter {chapter_number}"
            
        except Exception as e:
            self.logger.warning(f"Error creating fallback title: {e}")
            return f"Chapter {chapter_number}"

    def _create_fallback_title_from_scenes(
        self,
        scene_info: List[Dict[str, Any]],
        start_scene: int,
        end_scene: int,
        chapter_num: int
    ) -> str:
        """
        Create a fallback title based on scene titles in the chapter.

        Args:
            scene_info: All scene information
            start_scene: First scene in chapter
            end_scene: Last scene in chapter
            chapter_num: Chapter number

        Returns:
            Generated chapter title
        """
        try:
            # Find scenes in this chapter
            chapter_scenes = [
                s for s in scene_info
                if start_scene <= s['scene_number'] <= end_scene
            ]

            if chapter_scenes:
                # Use first scene title as chapter title
                first_scene_title = chapter_scenes[0].get('title', '')
                if first_scene_title:
                    return first_scene_title

            # Generic fallback
            return f"Chapter {chapter_num}"

        except Exception as e:
            self.logger.warning(f"Error creating fallback title: {e}")
            return f"Chapter {chapter_num}"

    def _store_chapters(self, context: PipelineStageContext, chapters: List[Dict[str, Any]]) -> int:
        """
        Store chapters in the database.
        
        Args:
            context: Stage execution context
            chapters: List of chapter data
            
        Returns:
            Number of chapters stored
        """
        draft_id = context.draft_id
        
        if not chapters:
            return 0
        
        try:
            chapters_stored = 0
            
            db_connection = self.get_database_connection(context)
            with db_connection as conn:
                cursor = conn.cursor()
                # Clear existing chapters for this draft
                cursor.execute("DELETE FROM chapters WHERE draft_id = %s", (draft_id,))
                
                # Prepare bulk insert data with ULID generation
                chapter_data = []
                current_time = datetime.now()

                for chapter in chapters:
                    chapter_id = str(ULID())  # Generate unique ULID for each chapter

                    # Serialize scene_titles to JSON string
                    scene_titles = chapter.get('scene_titles', [])
                    scene_titles_json = json.dumps(scene_titles) if scene_titles else None

                    chapter_data.append((
                        chapter_id,  # id column (ULID)
                        draft_id,
                        chapter.get('chapter_number', 1),
                        chapter.get('title', 'Untitled Chapter'),
                        chapter.get('content', ''),
                        chapter.get('word_count', 0),           # v2.0: chapter word count
                        chapter.get('start_scene'),             # v2.0: first scene in chapter
                        chapter.get('end_scene'),               # v2.0: last scene in chapter
                        chapter.get('scene_count', 0),          # v2.0: number of scenes
                        scene_titles_json,                      # v2.0: scene titles as JSON
                        current_time,  # created_at
                        current_time   # updated_at
                    ))

                # Bulk insert chapters with all required fields (v2.0 includes metadata)
                if chapter_data:
                    cursor.executemany("""
                        INSERT INTO chapters (
                            id, draft_id, chapter_number, title, content,
                            word_count, start_scene, end_scene, scene_count, scene_titles,
                            created_at, updated_at
                        )
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """, chapter_data)

                    chapters_stored = cursor.rowcount

                    # Only commit if we're NOT in a managed transaction (i.e., got our own connection)
                    if not context.get('connection'):
                        conn.commit()

            self.logger.info(f"Stored {chapters_stored} chapters for draft {draft_id} [transaction managed: {bool(context.get('connection'))}]")
            return chapters_stored
            
        except Exception as e:
            self.logger.error(f"Failed to store chapters for draft {draft_id}: {e}")
            raise
    
    def get_chaptering_statistics(self, draft_id: str) -> Dict[str, Any]:
        """
        Get statistics about the chaptering process.
        
        Args:
            draft_id: UUID of the draft
            
        Returns:
            Chaptering statistics
        """
        try:
            conn = self.db_pool.getconn()
            
            with conn.cursor() as cursor:
                # Get chapter statistics
                cursor.execute("""
                    SELECT 
                        COUNT(*) as chapter_count,
                        AVG(LENGTH(content)) as avg_chapter_length,
                        MIN(LENGTH(content)) as min_chapter_length,
                        MAX(LENGTH(content)) as max_chapter_length,
                        SUM(LENGTH(content)) as total_content_length
                    FROM chapters
                    WHERE draft_id = %s
                """, (draft_id,))
                
                result = cursor.fetchone()
                
                if result:
                    count, avg_len, min_len, max_len, total_len = result
                    
                    # Convert to word counts (approximate)
                    avg_words = int(avg_len / 5) if avg_len else 0  # ~5 chars per word
                    min_words = int(min_len / 5) if min_len else 0
                    max_words = int(max_len / 5) if max_len else 0
                    total_words = int(total_len / 5) if total_len else 0
                    
                    stats = {
                        'chapter_count': count,
                        'avg_chapter_words': avg_words,
                        'min_chapter_words': min_words,
                        'max_chapter_words': max_words,
                        'total_words': total_words
                    }
                else:
                    stats = {
                        'chapter_count': 0,
                        'avg_chapter_words': 0,
                        'min_chapter_words': 0,
                        'max_chapter_words': 0,
                        'total_words': 0
                    }
                
                # Get chapter titles
                cursor.execute("""
                    SELECT chapter_number, title
                    FROM chapters
                    WHERE draft_id = %s
                    ORDER BY chapter_number
                """, (draft_id,))
                
                titles = cursor.fetchall()
                stats['chapter_titles'] = [{'number': num, 'title': title} for num, title in titles]
            
            self.db_pool.putconn(conn)
            return stats
            
        except Exception as e:
            self.logger.error(f"Failed to get chaptering statistics for draft {draft_id}: {e}")
            return {'error': str(e)}
    
    def rechapter_manuscript(self, draft_id: str, new_mode: str = 'flexible', 
                           new_target_length: int = 2500) -> Dict[str, Any]:
        """
        Re-run chaptering with different parameters.
        
        Args:
            draft_id: UUID of the draft
            new_mode: New chaptering mode
            new_target_length: New target chapter length
            
        Returns:
            Re-chaptering results
        """
        try:
            # Delete existing chapters
            conn = self.db_pool.getconn()
            
            with conn.cursor() as cursor:
                cursor.execute("DELETE FROM chapters WHERE draft_id = %s", (draft_id,))
                deleted_count = cursor.rowcount
                conn.commit()
            
            self.db_pool.putconn(conn)
            
            self.logger.info(f"Deleted {deleted_count} existing chapters for re-chaptering")
            
            # Re-run chaptering
            result = self.run(draft_id, new_mode, new_target_length)
            result['rechaptered'] = True
            result['deleted_chapters'] = deleted_count
            
            return result
            
        except Exception as e:
            self.logger.error(f"Failed to rechapter manuscript for draft {draft_id}: {e}")
            return {
                'success': False,
                'error': str(e),
                'draft_id': draft_id
            }
